namespace MenuRealApi.Models
{
    public enum Country
    {
        Portugal = 1,
        Spain = 2,
        France = 3,
        UnitedKingdom = 4,
        Ireland = 5,
        Iceland = 6,
        Belgium = 7,
        Netherlands = 8,
        Germany = 9,
        Switzerland = 10,
        Italy = 11,
        Monaco = 12,
        Malta = 13,
        Norway = 14,
        Denmark = 15,
        CzechRepublic = 16,
        Austria = 17,
        Slovenia = 18,
        Croatia = 19,
        BozniaAndHerzegovina = 20,
        Liechenstein = 21,
        Montenegro = 22,
        Albania = 23,
        Greece = 24,
        Macedonia = 25,
        Serbia = 26,
        Hungary = 27,
        Slovakia = 28,
        Poland = 29,
        Sweden = 30,
        Lithuania = 31,
        Latvia = 32,
        Estonia = 33,
        Belarus = 34,
        Ukraine = 35,
        Moldova = 36,
        Romania = 37,
        Bulgaria = 38,
        Finland = 39,
        Andorra = 40,
        Luxemburg = 41,
    }
}